### ISSUE TITLE
Flush ruleset

### ISSUE THREAD

**Issue by blead** [Frzk/ansible-role-nftables#2]
I am using Debian GNU/Linux 9 (stretch) image on GCP and restarting the service does not automatically flush the ruleset.

Would it be possible to revert https://github.com/Frzk/ansible-role-nftables/commit/f2047a3d42122f52907d14536d0863468472eb81?

**Comment by Frzk** [comment]
Oh I see ! The `.service` file only asks nftables to flush the ruleset when **stopping** the service (`ExecStop`), not when reloading it.

My mistake. I'm reverting this.

**Comment by blead** [comment]
Thank you for your fast response!
